name: C++ CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Install libkqueue
      run: |
        git clone https://github.com/mheily/libkqueue.git
        cd libkqueue
        cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib .
        make
        sudo make install
        sudo ldconfig

    - name: Build project
      id: build
      run: make

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ircserve
        path: ircserve

    - name: IRC notification - Success
      if: success()
      uses: Gottox/irc-message-action@v2
      with:
        server: 'irc.libera.chat'
        channel: '#ircserve-builds'
        nickname: 'github-bot'
        message: ' Build succeeded for ${{ github.repository }} by ${{ github.actor }} - ${{ github.event.head_commit.message }}'

    - name: IRC notification - Failure
      if: failure()
      uses: Gottox/irc-message-action@v2
      with:
        server: 'irc.libera.chat'
        channel: '#ircserve-builds'
        nickname: 'github-bot'
        message: ' Build failed for ${{ github.repository }} by ${{ github.actor }} - ${{ github.event.head_commit.message }}'
